// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolWebInternalAPI.Infrastructure.Data;

#nullable disable

namespace SchoolWebInternalAPI.Infrastructure.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    [Migration("20251204175817_AddHomePageTable")]
    partial class AddHomePageTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("SchoolWebInternalAPI.Domain.Entities.Pages.HomePage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AboutHtml")
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<string>("AboutImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("AboutSubtitle")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("AboutTitle")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeroButtonText")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("HeroButtonUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("HeroImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("HeroSubtitle")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("HeroTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Highlight1Icon")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Highlight1Text")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Highlight1Title")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Highlight2Icon")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Highlight2Text")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Highlight2Title")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Highlight3Icon")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Highlight3Text")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Highlight3Title")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OgImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("SeoDescription")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("SeoTitle")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HomePages", (string)null);
                });

            modelBuilder.Entity("SchoolWebInternalAPI.Domain.Entities.PagesCSM.ContactPageContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("InfoHtml")
                        .HasColumnType("TEXT");

                    b.Property<string>("MapEmbedUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("OgImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("SeoDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("SeoTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subtitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ContactPageContents");
                });

            modelBuilder.Entity("SchoolWebInternalAPI.Domain.Entities.PagesCSM.FooterContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FooterText")
                        .HasColumnType("TEXT");

                    b.Property<string>("NewsletterText")
                        .HasColumnType("TEXT");

                    b.Property<string>("NewsletterTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("SocialLinksJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UsefulLinksJson")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FooterContents");
                });

            modelBuilder.Entity("SchoolWebInternalAPI.Domain.Entities.PagesCSM.HistoryPageContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentHtml")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OgImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("SeoDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("SeoTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("SideImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subtitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HistoryPageContents");
                });

            modelBuilder.Entity("SchoolWebInternalAPI.Domain.Entities.PagesCSM.HomePageContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AboutHtml")
                        .HasColumnType("TEXT");

                    b.Property<string>("AboutImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("AboutSubtitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("AboutTitle")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeroButtonText")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeroButtonUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeroImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeroSubtitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeroTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Highlight1Icon")
                        .HasColumnType("TEXT");

                    b.Property<string>("Highlight1Text")
                        .HasColumnType("TEXT");

                    b.Property<string>("Highlight1Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("Highlight2Icon")
                        .HasColumnType("TEXT");

                    b.Property<string>("Highlight2Text")
                        .HasColumnType("TEXT");

                    b.Property<string>("Highlight2Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("Highlight3Icon")
                        .HasColumnType("TEXT");

                    b.Property<string>("Highlight3Text")
                        .HasColumnType("TEXT");

                    b.Property<string>("Highlight3Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("OgImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("SeoDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("SeoTitle")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HomePageContents");
                });

            modelBuilder.Entity("SchoolWebInternalAPI.Domain.Entities.PagesCSM.LinksPageContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IntroHtml")
                        .HasColumnType("TEXT");

                    b.Property<string>("LinksHtml")
                        .HasColumnType("TEXT");

                    b.Property<string>("OgImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("SeoDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("SeoTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LinksPageContents");
                });

            modelBuilder.Entity("SchoolWebInternalAPI.Domain.Entities.PagesCSM.MissionPageContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("IntroHtml")
                        .HasColumnType("TEXT");

                    b.Property<string>("MissionHtml")
                        .HasColumnType("TEXT");

                    b.Property<string>("OgImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("SeoDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("SeoTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MissionPageContents");
                });

            modelBuilder.Entity("SchoolWebInternalAPI.Domain.Entities.PagesCSM.OrganizationPageContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionHtml")
                        .HasColumnType("TEXT");

                    b.Property<string>("OgImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrgChartFileUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrgChartImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("SeoDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("SeoTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("OrganizationPageContents");
                });

            modelBuilder.Entity("SchoolWebInternalAPI.Domain.Entities.PagesCSM.SiteSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("TEXT");

                    b.Property<string>("CookieBannerText")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultLanguage")
                        .HasColumnType("TEXT");

                    b.Property<string>("FacebookUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("FaviconUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TwitterUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("YoutubeUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SiteSettings");
                });

            modelBuilder.Entity("SchoolWebInternalAPI.Domain.Entities.PagesCSM.TeachersPageContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeroImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("IntroHtml")
                        .HasColumnType("TEXT");

                    b.Property<string>("OgImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("PageSubtitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("PageTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SeoDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("SeoTitle")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TeachersPageContents");
                });

            modelBuilder.Entity("SchoolWebInternalAPI.Domain.Entities.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bio")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Teachers");
                });
#pragma warning restore 612, 618
        }
    }
}
